version: "3.7"

services:
  nginx_frontend:
    image: docker.pkg.github.com/veerendra2/python-flask-mongodb-app/flask-app:latest
    container_name: flask-app
    ports:
      - "80:80"
    depends_on:
      - "mongo_db"
    networks:
      - back-tier

  mongo_db:
    image: docker.pkg.github.com/veerendra2/python-flask-mongodb-app/mongo-db:latest
    container_name: mongodb_log
    environment:
      MONGO_INITDB_ROOT_USERNAME: "Phief3me"
      MONGO_INITDB_ROOT_PASSWORD: "sigma"
      MONGODB_SERVICE_SERVICE_HOST: "mongo-db"
      MONGODB_SERVICE_SERVICE_PORT: "27017"
    volumes:
      - "db-data:/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  back-tier:
